### ISSUE TITLE
Desarrollo de Bitácora 

### ISSUE THREAD

**Issue by ItzelCP** [ItzelCP/Jar-mui-Hidalguense#15]
Desarrollo de Bitácora

**Comment by victoria0125** [comment]
[BITACORA DE PROYECTO.xlsx](https://github.com/ItzelCP/Jar-mui-Hidalguense/files/2270945/BITACORA.DE.PROYECTO.xlsx)

**Comment by victoria0125** [comment]
Listo

**Comment by victoria0125** [comment]
Listo

**Comment by victoria0125** [comment]
listo
