### ISSUE TITLE
Investigacion de la Region de Ixmiquilpan 

### ISSUE THREAD

**Issue by ItzelCP** [ItzelCP/Jar-mui-Hidalguense#4]
# Investigacion para marco teorico de la region de Ixmiquilpan

**Comment by Eve9no** [comment]
LOCALIZACIÓN
La ciudad de Ixmiquilpan tiene las siguientes coordenadas geográficas, 20° 29' latitud norte, 99° 13' latitud oeste y se encuentra ubicado a 1,700 metros sobre el nivel del mar (msnm).
Sus colindancias son: 

Al norte, con los municipios de Zimapán, Nicolás Flores y Cardonal; al este, con Cardonal y Santiago de Anaya; al sur, con Santiago de Anaya, San Salvador, Chilcuautla y Alfajayucan y al oeste, con Alfajayucan, Tasquillo y Zimapán.
ARTESANIAS
Ixmiquilpan es una de las tierras hidalguenses más importantes a nivel gastronomía, destinos y artesanía. Todas y cada una de ellas se obtienen de fibra de maguey como ayates, mecapales, que son fajas de cuero que utilizan los mozos de cuerda para llevar cargas, morrales que a veces se llevan los turistas para guardar un pedacito de Hidalgo, variedad de lazos y reatas para amarrar a los animales o practicar el jaripeo, tapetes con bellos diseños bordados para la puerta del hogar, escobetas, mecates, jorongos, cobijas para los fríos de diciembre.
 En sus distintas regiones se trabaja la artesanía, ya que ésta, es considerada su principal actividad para subsistir y preservar los conocimientos adquiridos por los antepasados de la región, siempre interesados en la cultura y las tradiciones. Como por ejemplo en La Cruz Blanca, en la cual se trabaja el carrizo. En Orizabita, en la cual la principal actividad artesanal es la alfarería. El Ninth, en el cual se elaboran miniaturas de concha de abulón con madera y en San Nicolás donde se elaboran los fantásticos bordados.
El Ninth, un lugar en las afueras de Ixmiquilpan cuyo nombre deriva del otomí, mágico lugar donde se elaboran artesanías con fibras de maguey desde épocas prehispánicas para los españoles en ese entonces, como cuerdas de guitarra. De aquí surgió la tradición de arreglar estas, lo cual se hacía con hueso, hasta que alguien comenzó integrando las conchas y así nació la tradición de la incrustación de concha de abulón como elemento decorativo sobre la madera de enebro, convertidas en objetos como pulseras, prendedores, aros, espejos, collares, alhajeros, llaveros, tableros de ajedrez, dominós, guitarras, violines, arpas y pianos de cola.

**Comment by Eve9no** [comment]
Listo!

**Comment by Eve9no** [comment]
Listo
