### ISSUE TITLE
Estadisticas Generales sobre Artesanias 

### ISSUE THREAD

**Issue by ItzelCP** [ItzelCP/Jar-mui-Hidalguense#9]
**Estadisticas Generales sobre Artesanias**

**Comment by victoria0125** [comment]
[Estadisticas-artesanias.docx](https://github.com/ItzelCP/Jar-mui-Hidalguense/files/2152122/Estadisticas-artesanias.docx)

**Comment by victoria0125** [comment]
Terminado
